[project]
name = "poc-xss-django-allauth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django==4.2",
    "django-allauth[socialaccount]==0.63.5",
]
